
title: MachineSight
# email: dadadavidoluwaniyinye@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to MachineSight. Here you will find insights, and tutorials on computer vision techniques.
url: "machinesight.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# twitter_username: jekyllrb
github_username:  MachineSight

# Build settings
theme: minima
plugins:
  - jekyll-feeds
  - jekyll-sitemap

google_analytics: G-X2SZPGZPCM


